2020-04-18 16:27:53,848 INFO: RavenScout startup [in C:\Users\Daniel\Documents\GitHub\RavenScout\app\__init__.py:51]
2020-04-18 16:50:24,218 INFO: RavenScout startup [in C:\Users\Daniel\Documents\GitHub\RavenScout\app\__init__.py:51]
2020-04-18 16:50:26,831 ERROR: Exception on /home [GET] [in c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Daniel\Documents\GitHub\RavenScout\app\routes.py", line 28, in home
    return render_template('home.html', title='Home |', form=form,
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Daniel\Documents\GitHub\RavenScout\app\templates\home.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Daniel\Documents\GitHub\RavenScout\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 12, in block "body"
  File "C:\Users\Daniel\Documents\GitHub\RavenScout\app\templates\base.html", line 28, in block "navbar"
    <li><a href="{{ url_for('teams') }}">Teams</a></li>
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\daniel\appdata\local\programs\python\python38-32\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'teams'. Did you mean 'latest' instead?
2020-04-18 16:51:14,393 INFO: RavenScout startup [in C:\Users\Daniel\Documents\GitHub\RavenScout\app\__init__.py:51]
2020-04-18 17:02:23,423 INFO: RavenScout startup [in C:\Users\Daniel\Documents\GitHub\RavenScout\app\__init__.py:51]
2020-04-19 18:31:41,829 INFO: RavenScout startup [in D:\Code\RavenScout\app\__init__.py:51]
2020-04-19 18:31:52,982 INFO: RavenScout startup [in D:\Code\RavenScout\app\__init__.py:51]
2020-04-19 18:33:36,241 INFO: RavenScout startup [in D:\Code\RavenScout\app\__init__.py:51]
